import { Manrope } from "next/font/google";
import "./globals.css";


const manrope = Manrope({ 
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  variable: "--font-manrope"
 });

export const metadata = {
  title: "Kinzzle",
  description: "Generated by create next app",
  icons: "/favicon.svg?v=4"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={`${manrope.variable} dark manrope`}>
        {children}
      </body>
    </html>
  );
}
